name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set timestamp
      run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build docker image
      run: docker build -t random_fact_generator:${{ env.IMAGE_TAG }} ./random_fact_generator/main.py

    - name: Tag docker image
      run: docker tag random_fact_generator:${{ env.IMAGE_TAG }} random_fact_generator:${{ env.IMAGE_TAG }}
      
    - name : Push docker image to repository
      run: docker push random_fact_generator:${{ env.IMAGE_TAG }}
