name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set timestamp
      run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Build the broker Docker image
      run: docker build ./wikimedia_messages/kafka_broker --file ./wikimedia_messages/kafka_broker/Dockerfile --tag broker:${{ env.IMAGE_TAG }}

    - name: Build the zookeeper Docker image
      run: docker build ./wikimedia_messages/kafka_zookeeper --file ./wikimedia_messages/kafka_zookeeper/Dockerfile --tag zookeeper:${{ env.IMAGE_TAG }}

    - name: Build the consumer Docker image
      run: docker build ./wikimedia_messages/kafka_consumer --file ./wikimedia_messages/kafka_consumer/Dockerfile --tag consumer:${{ env.IMAGE_TAG }}

    - name: Build the producer Docker image
      run: docker build ./wikimedia_messages/kafka_producer --file ./wikimedia_messages/kafka_producer/Dockerfile --tag producer:${{ env.IMAGE_TAG }}

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push broker Docker image
      run: docker push broker:${{ env.IMAGE_TAG }}

    - name: Push zookeeper Docker image
      run: docker push zookeeper:${{ env.IMAGE_TAG }}

    - name: Push consumer Docker image
      run: docker push consumer:${{ env.IMAGE_TAG }}

    - name: Push producer Docker image
      run: docker push producer:${{ env.IMAGE_TAG }}

    - name: Deploy using Docker Compose
      run: docker-compose -f ./wikimedia_messages/docker-compose.yaml up
